/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jiangyt_library_libitop_UvcCamera */

#ifndef _Included_com_jiangyt_library_libitop_UvcCamera
#define _Included_com_jiangyt_library_libitop_UvcCamera
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jiangyt_library_libitop_UvcCamera
 * Method:    open
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_jiangyt_library_libitop_UvcCamera_open
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_jiangyt_library_libitop_UvcCamera
 * Method:    init
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_jiangyt_library_libitop_UvcCamera_init
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     com_jiangyt_library_libitop_UvcCamera
 * Method:    streamon
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jiangyt_library_libitop_UvcCamera_streamon
  (JNIEnv *, jclass);

/*
 * Class:     com_jiangyt_library_libitop_UvcCamera
 * Method:    dqbuf
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_jiangyt_library_libitop_UvcCamera_dqbuf
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_jiangyt_library_libitop_UvcCamera
 * Method:    yuvtorgb
 * Signature: ([B[BII)I
 */
JNIEXPORT jint JNICALL Java_jiangyt_library_libitop_UvcCamera_yuvtorgb
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jint, jint);

/*
 * Class:     com_jiangyt_library_libitop_UvcCamera
 * Method:    qbuf
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_jiangyt_library_libitop_UvcCamera_qbuf
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_jiangyt_library_libitop_UvcCamera
 * Method:    videoinit
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_jiangyt_library_libitop_UvcCamera_videoinit
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_jiangyt_library_libitop_UvcCamera
 * Method:    videostart
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_jiangyt_library_libitop_UvcCamera_videostart
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_jiangyt_library_libitop_UvcCamera
 * Method:    videoclose
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jiangyt_library_libitop_UvcCamera_videoclose
  (JNIEnv *, jclass);

/*
 * Class:     com_jiangyt_library_libitop_UvcCamera
 * Method:    streamoff
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jiangyt_library_libitop_UvcCamera_streamoff
  (JNIEnv *, jclass);

/*
 * Class:     com_jiangyt_library_libitop_UvcCamera
 * Method:    release
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jiangyt_library_libitop_UvcCamera_release
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
