/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jiangyt_library_libitop_ItopStepMotor */

#ifndef _Included_com_jiangyt_library_libitop_ItopStepMotor
#define _Included_com_jiangyt_library_libitop_ItopStepMotor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jiangyt_library_libitop_ItopStepMotor
 * Method:    open
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_jiangyt_library_libitop_ItopStepMotor_open
  (JNIEnv *, jobject);

/*
 * Class:     com_jiangyt_library_libitop_ItopStepMotor
 * Method:    close
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_jiangyt_library_libitop_ItopStepMotor_close
  (JNIEnv *, jobject);

/*
 * Class:     com_jiangyt_library_libitop_ItopStepMotor
 * Method:    ioCtl
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_jiangyt_library_libitop_ItopStepMotor_ioCtl
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
