/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jiangyt_library_libitop_ItopRfid */

#ifndef _Included_com_jiangyt_library_libitop_ItopRfid
#define _Included_com_jiangyt_library_libitop_ItopRfid
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jiangyt_library_libitop_ItopRfid
 * Method:    open
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_jiangyt_library_libitop_ItopRfid_open
  (JNIEnv *, jobject);

/*
 * Class:     com_jiangyt_library_libitop_ItopRfid
 * Method:    close
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_jiangyt_library_libitop_ItopRfid_close
  (JNIEnv *, jobject);

/*
 * Class:     com_jiangyt_library_libitop_ItopRfid
 * Method:    ioCtl
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_jiangyt_library_libitop_ItopRfid_ioCtl
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_jiangyt_library_libitop_ItopRfid
 * Method:    read
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_com_jiangyt_library_libitop_ItopRfid_read
  (JNIEnv *, jobject);

/*
 * Class:     com_jiangyt_library_libitop_ItopRfid
 * Method:    readCardNum
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_jiangyt_library_libitop_ItopRfid_readCardNum
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
