/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jiangyt_simple_itop_relay_ItopRelay */

#ifndef _Included_com_jiangyt_simple_itop_relay_ItopRelay
#define _Included_com_jiangyt_simple_itop_relay_ItopRelay
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jiangyt_simple_itop_relay_ItopRelay
 * Method:    open
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_jiangyt_library_libitop_ItopRelay_open
  (JNIEnv *, jobject);

/*
 * Class:     com_jiangyt_simple_itop_relay_ItopRelay
 * Method:    close
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_jiangyt_library_libitop_ItopRelay_close
  (JNIEnv *, jobject);

/*
 * Class:     com_jiangyt_simple_itop_relay_ItopRelay
 * Method:    ioCtl
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_jiangyt_library_libitop_ItopRelay_ioCtl
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
