/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jiangyt_library_ffmpeg_FFMpegRtmp */

#ifndef _Included_com_jiangyt_library_ffmpeg_FFMpegRtmp
#define _Included_com_jiangyt_library_ffmpeg_FFMpegRtmp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jiangyt_library_ffmpeg_FFMpegRtmp
 * Method:    setCallback
 * Signature: (Lcom/jinmao/cloud/app/ffmpeg/PushCallback;)I
 */
JNIEXPORT jint JNICALL Java_com_jiangyt_library_ffmpeg_FFMpegRtmp_setCallback
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_jiangyt_library_ffmpeg_FFMpegRtmp
 * Method:    getAvcodecConfiguration
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jiangyt_library_ffmpeg_FFMpegRtmp_getAvcodecConfiguration
  (JNIEnv *, jobject);

/*
 * Class:     com_jiangyt_library_ffmpeg_FFMpegRtmp
 * Method:    pushRtmpFile
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_jiangyt_library_ffmpeg_FFMpegRtmp_pushRtmpFile
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_jiangyt_library_ffmpeg_FFMpegRtmp
 * Method:    stopPushRtmp
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jiangyt_library_ffmpeg_FFMpegRtmp_stopPushRtmp
        (JNIEnv *, jobject);

/*
 * Class:     com_jiangyt_library_ffmpeg_FFMpegRtmp
 * Method:    initVideo
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_jiangyt_library_ffmpeg_FFMpegRtmp_initVideo
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_jiangyt_library_ffmpeg_FFMpegRtmp
 * Method:    onFrameCallback
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_com_jiangyt_library_ffmpeg_FFMpegRtmp_onFrameCallback
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_jiangyt_library_ffmpeg_FFMpegRtmp
 * Method:    close
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_jiangyt_library_ffmpeg_FFMpegRtmp_close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
