/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jiangyt_library_libitop_ItopL9110s */

#ifndef _Included_com_jiangyt_library_libitop_ItopL9110s
#define _Included_com_jiangyt_library_libitop_ItopL9110s
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jiangyt_library_libitop_ItopL9110s
 * Method:    open
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_jiangyt_library_libitop_ItopL9110s_open
  (JNIEnv *, jobject);

/*
 * Class:     com_jiangyt_library_libitop_ItopL9110s
 * Method:    close
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_jiangyt_library_libitop_ItopL9110s_close
  (JNIEnv *, jobject);

/*
 * Class:     com_jiangyt_library_libitop_ItopL9110s
 * Method:    ioCtl
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_jiangyt_library_libitop_ItopL9110s_ioCtl
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
