/* DO NOT EDIT THIS FILE - it is machine generated */
#include <stdio.h>
#include <stdlib.h>
#include <fcntl.h>
#include <errno.h>
#include <unistd.h>
#include <string.h>
#include <stdint.h>
#include <termios.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <sys/ioctl.h>
#include <android/log.h>
#include "itop_l9110s.h"

#undef TCSAFLUSH
#define TCSAFLUSH TCSETSF
#ifndef _TERMIOS_H_
#define _TERMIOS_H_
#endif

int fd = 0;
int flag = -1;
/*
 * Class:     com_jiangyt_library_libitop_ItopL9110s
 * Method:    open
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_jiangyt_library_libitop_ItopL9110s_open
  (JNIEnv *env, jobject obj) {
    if (fd <= 0) {
        fd = open("/dev/l9110s_ctl", O_RDWR | O_NDELAY | O_NOCTTY);
    }
    if (fd <= 0) {
        __android_log_print(ANDROID_LOG_INFO, "serial", "open /dev/l9110s_ctl Error");
        flag = -1;
    } else {
        __android_log_print(ANDROID_LOG_INFO, "serial", "open /dev/l9110s_ctl Success fd = %d", fd);
        flag = 0;
    }
    return flag;
}

/*
 * Class:     com_jiangyt_library_libitop_ItopL9110s
 * Method:    close
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_jiangyt_library_libitop_ItopL9110s_close
  (JNIEnv *env, jobject obj) {
    if (fd > 0) close(fd);
    return 0;
}

/*
 * Class:     com_jiangyt_library_libitop_ItopL9110s
 * Method:    ioCtl
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_jiangyt_library_libitop_ItopL9110s_ioCtl
  (JNIEnv *env, jobject obj, jint pin, jint cmd) {
    ioctl(fd, pin, cmd);
    return 0;
}